INSERT ALL
INTO AIRPLANES(AIRPLANE_TAG,AIRPLANE_CAPACITY,AIRPLANE_MAKE,AIRPLANE_MODEL)
VALUES(1,'100','AIRBUS','321'    )
INTO AIRPLANES(AIRPLANE_TAG,AIRPLANE_CAPACITY,AIRPLANE_MAKE,AIRPLANE_MODEL)
VALUES(2,'100','AIRBUS','321'    )
INTO AIRPLANES(AIRPLANE_TAG,AIRPLANE_CAPACITY,AIRPLANE_MAKE,AIRPLANE_MODEL)
VALUES(3,'120','AIRBUS','320'    )
INTO AIRPLANES(AIRPLANE_TAG,AIRPLANE_CAPACITY,AIRPLANE_MAKE,AIRPLANE_MODEL)
VALUES(4,'120','AIRBUS','320'    )
INTO AIRPLANES(AIRPLANE_TAG,AIRPLANE_CAPACITY,AIRPLANE_MAKE,AIRPLANE_MODEL)
VALUES(5,'50' ,'Eembraer','190'   )
INTO AIRPLANES(AIRPLANE_TAG,AIRPLANE_CAPACITY,AIRPLANE_MAKE,AIRPLANE_MODEL)
VALUES(6,'50' ,'Eembraer','190'   )
SELECT * FROM DUAL;