CREATE TABLE "AIRPLANES"
(
    "AIRPLANE_TAG" 			NUMBER 			NOT NULL,
    "AIRPLANE_CAPACITY" 	CHAR(3) 		NOT	NULL,
    "AIRPLANE_MAKE" 		VARCHAR(25) 	NOT NULL,
    "AIRPLANE_MODEL" 		VARCHAR(25) 	NOT NULL,
	PRIMARY KEY("AIRPLANE_TAG")
)/

CREATE TABLE "AIRPORTS"
(
    "AIRPORT_CODE" 		CHAR(3) 		NOT	NULL,
    "AIRPORT_NAME" 		VARCHAR(50) 	NOT NULL,
    "AIRPORT_CITY" 		VARCHAR(25) 	NOT NULL,
    "AIRPORT_STATE"		CHAR(2) 		NOT NULL,
    "AIRPORT_COUNTRY"	VARCHAR(25) 	NOT NULL,
	PRIMARY KEY("AIRPORT_CODE")
)/

CREATE TABLE "FLIGHTS"
(
    "AIRPLANE_TAG" 			NUMBER 			NOT NULL,
    "DEPARTURE_AIRPORT" 	CHAR(3) 		NOT NULL,
    "ARRIVAL_AIRPORT" 		CHAR(3) 		NOT NULL,
    "DEPARTURE_DATE"		DATE 			NOT NULL,
    "ARRIVAL_DATE"			DATE 			NOT NULL,
    "FLIGHT_MILLAGE"		NUMBER		 	NOT NULL,
    "FLIGHT_PRICE"			NUMBER		 	NOT NULL,
    "FLIGHT_TIME"			TIMESTAMP	 	,
	PRIMARY KEY("AIRPLANE_TAG","DEPARTURE_DATE"),
    FOREIGN KEY("DEPARTURE_AIRPORT") REFERENCES "AIRPORTS"("AIRPORT_CODE"),
    FOREIGN KEY("ARRIVAL_AIRPORT") REFERENCES "AIRPORTS"("AIRPORT_CODE")
)/

CREATE TABLE "STAFF"
(
    "STAFF_ID" 			NUMBER 			NOT NULL,
    "STAFF_FIRST" 		VARCHAR(25) 	NOT	NULL,
    "STAFF_LAST" 		VARCHAR(25) 	NOT NULL,
    "STAFF_DOB" 		DATE		 	NOT NULL,
    "STAFF_SSN"			CHAR(11) 		NOT NULL,
    "STAFF_TITLE"		VARCHAR(25) 	NOT NULL,
	PRIMARY KEY("STAFF_ID")
)/

CREATE TABLE "CUSTOMERS"
(
    "CUSTOMER_ID" 			NUMBER 			NOT NULL,
    "CUSTOMER_FIRST" 		VARCHAR(25)		NOT	NULL,
    "CUSTOMER_LAST" 		VARCHAR(25) 	NOT NULL,
    "CUSTOMER_DOB" 			DATE		 	NOT NULL,
    "CUSTOMER_PASSPORT"		CHAR(15) 		NOT NULL,
	"CUSTOMER_AGE"			NUMBER(3),		
	PRIMARY KEY("CUSTOMER_ID")
)/


CREATE TABLE "RESERVATIONS"
(
    "RESERVATION_ID" 	NUMBER 			NOT NULL,
    "CUSTOMER_ID" 		NUMBER 			NOT NULL,
    "AIRPLANE_TAG" 		NUMBER		 	NOT NULL,
	"DEPARTURE_DATE"	DATE			NOT NULL,
    "SEAT_ID" 			NUMBER			NOT NULL,
    "CHECKIN_ID"		NUMBER	 		NOT NULL,
	PRIMARY KEY("RESERVATION_ID"),
	FOREIGN KEY("CUSTOMER_ID") REFERENCES "CUSTOMERS"("CUSTOMER_ID"),
    FOREIGN KEY("AIRPLANE_TAG","DEPARTURE_DATE") REFERENCES "FLIGHTS"("AIRPLANE_TAG","DEPARTURE_DATE"),
    FOREIGN KEY("CHECKIN_ID") REFERENCES "CHECKIN"("CHECKIN_ID"),
	FOREIGN KEY("SEAT_ID") REFERENCES "SEATS"("SEAT_ID")
)/

ALTER TABLE RESERVATIONS
ADD CONSTRAINT SEATfk
ADD FOREIGN KEY("SEAT_ID") REFERENCES "SEATS"("SEAT_ID")


CREATE TABLE "SEATS"
(
    "SEAT_ID" 		NUMBER 		NOT NULL,
    "SEAT_NUMBER" 	CHAR(3) 	NOT	NULL,
    "SEAT_PRICE" 	NUMBER		NOT NULL,
	PRIMARY KEY("SEAT_ID")
)/

CREATE TABLE "FLIGHT_STAFF"
(
    "FLIGHTSTAFF_ID" 	NUMBER 		NOT NULL,
	"AIRPLANE_TAG" 		NUMBER		NOT NULL,
	"DEPARTURE_DATE"	DATE		NOT NULL,    
	"STAFF_ID" 			NUMBER		NOT NULL,
	PRIMARY KEY("FLIGHTSTAFF_ID"),
    FOREIGN KEY("AIRPLANE_TAG","DEPARTURE_DATE") REFERENCES "FLIGHTS"("AIRPLANE_TAG","DEPARTURE_DATE"),
	FOREIGN KEY("STAFF_ID") REFERENCES "STAFF"("STAFF_ID")
)/

CREATE TABLE "CHECKIN"
(
    "CHECKIN_ID" 		NUMBER 		NOT NULL,
    "CHECKED_LUGGAGE"	CHAR(1) 	DEFAULT 'N',
	CHECK ("CHECKED_LUGGAGE" IN ('Y','N')),
	PRIMARY KEY("CHECKIN_ID")
)/

ALTER TABLE CHECKIN
ADD "BOARDED_PLANE" CHAR(1) DEFAULT 'N'
ADD CHECK ("BOARDED_PLANE" IN ('Y','N')) ENABLE

