CREATE TABLE "STAFF"
(
	"STAFF_ID"				NUMBER			NOT NULL,
	"STAFF_FIRST"			VARCHAR(25)		NOT NULL,
	"STAFF_LAST"			VARCHAR(25) 	NOT NULL,
	"STAFF_DOB"				VARCHAR(25) 	NOT NULL,
	"STAFF_SSN" 			CHAR(11)		NOT NULL,
	"STAFF_POSITION"		VARCHAR(25)		NOT NULL,
	PRIMARY KEY("STAFF_ID")
)/

CREATE TABLE "CUSTOMERS"
(
	"CUSTOMER_ID"			NUMBER			NOT NULL,
	"CUSTOMER_FIRST"		VARCHAR(25)		NOT NULL,
	"CUSTOMER_LAST"			VARCHAR(25)		NOT NULL,
	"CUSTOMER_EMAIL"		VARCHAR(50)		NOT NULL,
	"CUSTOMER_ADDRESS"		VARCHAR(50)		NOT NULL,
	"CUSTOMER_CITY"		 	VARCHAR(25) 	NOT NULL,
	"CUSTOMER_ZIP"			CHAR(5)			NOT NULL,
	"CUSTOMER_STATE"		CHAR(2)			NOT NULL,
	"CUSTOMER_COUNTRY"		VARCHAR(25)		NOT NULL,
	PRIMARY KEY("CUSTOMER_ID")
)/

CREATE TABLE "PRODUCTS"
(
	"PRODUCT_ID"			NUMBER			NOT NULL,
	"PRODUCT_NAME"			VARCHAR(50)		NOT NULL,
	"PRODUCT_MANUFACTURER"	VARCHAR(25)		NOT NULL,
	"PRODUCT_DESCRIPTION"	VARCHAR(50)		NOT NULL,
	"PRODUCTDETAILS_SERIAL"	VARCHAR(12)			NULL,
	"PRODUCT_PRICE"			NUMBER			NOT NULL,
	"DEPARTMENT_ID"			NUMBER			NOT NULL,
	PRIMARY KEY("PRODUCT_ID"),
	FOREIGN KEY("PRODUCTDETAILS_SERIAL") REFERENCES "PRODUCT_DETAILS"("PRODUCTDETAILS_SERIAL"),
	FOREIGN KEY("DEPARTMENT_ID") REFERENCES "DEPARTMENTS"("DEPARTMENT_ID")
)/

CREATE TABLE "PRODUCT_DETAILS"
(
	"PRODUCTDETAILS_SERIAL"		VARCHAR(12)	NOT NULL,
	"PRODUCTDETAILS_PROCESSOR"	VARCHAR(30)	NULL,
	"PRODUCTDETAILS_SPEED"		VARCHAR(10)	NULL,
	"PRODUCTDETAILS_RAM"		NUMBER		NULL,
	"PRODUCTDETAILS_STORAGE"	NUMBER		NULL,
	"PRODUCTDETAILS_SCREEN"		NUMBER		NULL,
	PRIMARY KEY ("PRODUCTDETAILS_SERIAL")
)/

CREATE TABLE "LOCATIONS"
(
	"LOCATION_ID" 			NUMBER 			NOT NULL,
	"LOCATION_ADDRESS"	 	VARCHAR(25) 	NOT NULL,
	"LOCATION_CITY"		 	VARCHAR(25) 	NOT NULL,
	"LOCATION_STATE"		CHAR(2)			NOT NULL,
	"LOCATION_ZIP"			CHAR(5)			NOT NULL,
	"LOCATION_PHONE"		CHAR(12)		NOT NULL,
	PRIMARY KEY("LOCATION_ID")
)/

CREATE TABLE "TRANSACTIONS"
(
	"TRANSACTION_ID"		NUMBER			NOT NULL,
	"TRANSACTION_DATE"		DATE 			NOT NULL,
	"PRODUCT_ID"			NUMBER			NOT NULL,
	"STAFF_ID"				NUMBER			NOT NULL,
	"LOCATION_ID"			NUMBER			NOT NULL,
	"CUSTOMER_ID"			NUMBER			NOT NULL,
	"TRANSACTION_TOTAL"		NUMBER			NULL,
	PRIMARY KEY("TRANSACTION_ID"),
	FOREIGN KEY("PRODUCT_ID") REFERENCES "PRODUCTS"("PRODUCT_ID"),
	FOREIGN KEY("STAFF_ID") REFERENCES "STAFF"("STAFF_ID"),
	FOREIGN KEY("LOCATION_ID") REFERENCES "LOCATIONS"("LOCATION_ID"),
	FOREIGN KEY("CUSTOMER_ID") REFERENCES "CUSTOMERS"("CUSTOMER_ID")
)/

CREATE TABLE "STAFF_DEPARTMENTS"
(
	"STAFFDEPARTMENT_ID"	NUMBER			NOT NULL,
	"STAFF_ID" 				NUMBER			NOT NULL,
	"DEPARTMENT_ID"			NUMBER			NOT NULL,
	PRIMARY KEY("STAFFDEPARTMENT_ID"),
	FOREIGN KEY("STAFF_ID") REFERENCES "STAFF"("STAFF_ID"),
	FOREIGN KEY("DEPARTMENT_ID") REFERENCES "DEPARTMENTS"("DEPARTMENT_ID")
)/

CREATE TABLE "STAFF_LOCATIONS"
(
	"STAFFLOCATION_ID"		NUMBER			NOT NULL,
	"STAFF_ID"				NUMBER			NOT NULL,
	"LOCATION_ID"			NUMBER			NOT NULL,
	PRIMARY KEY("STAFFLOCATION_ID"),
	FOREIGN KEY("STAFF_ID") REFERENCES "STAFF"("STAFF_ID"),
	FOREIGN KEY("LOCATION_ID") REFERENCES "LOCATIONS"("LOCATION_ID")
)/

CREATE TABLE "RATINGS"
(
	"RATING_ID"				NUMBER			NOT NULL,
	"TRANSACTION_ID"		NUMBER			NOT NULL,
	"RATING"				NUMBER			NOT NULL,
	PRIMARY KEY("RATING_ID"),
	FOREIGN KEY("TRANSACTION_ID") REFERENCES "TRANSACTIONS"("TRANSACTION_ID"),
	CHECK("RATING" IN (5, 4, 3, 2, 1))
)/

CREATE TABLE "DEPARTMENTS"
(
	"DEPARTMENT_ID"			NUMBER			NOT NULL,
	"DEPARTMENT_NAME"		VARCHAR(25)		NOT NULL,
	PRIMARY KEY("DEPARTMENT_ID")
)/

